### PR TITLE
Skip already yielded addresses in MasterServerQuerier

### PR DESCRIPTION
**Pull request by Yepoleb**
Fixes looping requests and duplicates in the result.

### CODE REVIEW

**Comment by Holiverh** [comment]
Hi, thanks for this pull request. Sorry its taken so long to get looked at. Totally understand if you're long past caring. 😄

I like the change in change in theory because the behaviour is potentially problematic. Especially seeing as it's not even documented. However, I'm not convinced by this being the default behaviour for two reasons:

- I tried to keep `valve.source` as a low level interface for Source servers; so if the server returns duplicates then my initial thinking is that python-valve is in no position to change that. At least as the default behaviour that is.
- This change adds an ever growing set into a potentially very long running iterator. Again this isn't necessarily a problem, but I'm wary of this happening by default.

**Comment by Yepoleb** [comment]
The reason I implemented this was because the function regularly got stuck in a loop when the last address was a duplicate of a previous one. Actually removing the duplicates was just a convenient side effect.

I understand your concerns about the growing set, but I don't think it will ever become a problem. Storing the entire server list to display it is common in every game with a server browser. I estimated the maximum size per tuple at 64 bytes using `sys.getsizeof(("255.255.255.255", 65535))`, which means 20000 of them are just 1.28 MB or maybe 2 MB if we add the set overhead. That's an acceptable price to pay for making sure the function doesn't get stuck in an infinite loop in my opinion.

Maybe you have a better idea to prevent this from happening or Valve fixed their servers and this doesn't happen anymore, I highly doubt this though 😄. Thanks for coming back to work on the project again.

**Comment by Holiverh** [comment]
Points about resource usage noted. I might play around with this and maybe make it a separate interface into `MasterServerQuerier` before cutting a new release. But I do acknowledge that you (and others) are quite [eager for a new release](https://github.com/Holiverh/python-valve/issues/46).

**Comment by Holiverh** [comment]
Just FYI, I've adjusted this somewhat; see https://github.com/Holiverh/python-valve/compare/b371a9b69a12ef6e27b8fda41436e6b2b0583361...46f5ff9a641a9e5168ebf60640d947e916d21c3a. It keeps the old behaviour by default, but adds the `duplicates` option to `MasterServerQuerier.find` to control how duplicates are treated. `MasterServerQuerier.find(duplicates="stop")` is functionally equivalent to what this PR added.

**Comment by Yepoleb** [comment]
I don't want to argue about this too much, but I think the default behavior should be the one that doesn't break and returns the correct results, not the performant one. Otherwise this could lead to applications malfunctioning when deployed to another OS like in #39. The connection between too few results and removing duplicates is also more than counterintuitive.

**Pull request merged**
